# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_rustadd2_wrappers", use_symbols = TRUE, package_name = "rustadd2")

#' @docType package
#' @usage NULL
#' @useDynLib rustadd2, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
add <- function(x, y) .Call(wrap__add, x, y)

